# SyncAgentRules.ps1
# .clinerules 配下のモジュールルールを結合し、.agent および .AGENTS.md を生成・同期する

$ErrorActionPreference = 'Stop'

# プロジェクトルートを取得 (スクリプトの配置フォルダ)
$RootPath = Split-Path -Parent $MyInvocation.MyCommand.Path
if ([string]::IsNullOrEmpty($RootPath)) {
    $RootPath = Get-Location
}

$ClinerulesDir = Join-Path $RootPath ".clinerules"
$AgentFile = Join-Path $RootPath ".agent"
$AgentsMdFile = Join-Path $RootPath ".AGENTS.md"

Write-Host "--- AI Agent Rule Sync Script ---"
Write-Host "Source directory: $ClinerulesDir"

if (-not (Test-Path $ClinerulesDir)) {
    Write-Error ".clinerules directory not found at $ClinerulesDir"
    exit 1
}

# 1. .clinerules 配下の第一階層にある .md ファイルをソートして取得 (workflows等を除く)
$RuleFiles = Get-ChildItem -Path $ClinerulesDir -Filter "*.md" | Sort-Object Name

Write-Host "Found rule files:"
foreach ($file in $RuleFiles) {
    Write-Host "  - $($file.Name)"
}

# 2. .AGENTS.md のヘッダーを定義
$AgentsMdContent = @'
# AI Agent Project Guidelines (AGENTS.md)

> [!IMPORTANT]
> **AUTO-GENERATED FILE:**
> This file is automatically generated from the individual rule files in `.clinerules/`.
> **DO NOT EDIT THIS FILE DIRECTLY.**
> To modify or add rules, please edit the corresponding file under `.clinerules/` and run `.\SyncAgentRules.ps1` in the project root to synchronize.

---

'@

# 3. .agent のヘッダーを定義 (.agent はエージェント用システムプロンプトとして機能)
$AgentContent = @'
# AI Agent Core System Rules (.agent)
# AUTO-GENERATED from .clinerules/*.md - DO NOT EDIT DIRECTLY.
# Run .\SyncAgentRules.ps1 to synchronize.

============================================================
'@

# 4. 各ファイルをループ処理してコンテンツを結合
foreach ($file in $RuleFiles) {
    $content = Get-Content -Path $file.FullName -Raw -Encoding utf8
    
    # フロントマター (YAML front matter --- ... ---) がある場合は除去する
    if ($content -match "(?s)^---\r?\n(.*?)\r?\n---\r?\n(.*)$") {
        $cleanContent = $Matches[2].Trim()
    } else {
        $cleanContent = $content.Trim()
    }
    
    # .AGENTS.md 用のコンテンツ結合
    $AgentsMdContent = $AgentsMdContent + "`n## File: .clinerules/" + $file.Name + "`n`n" + $cleanContent + "`n`n---`n"
    
    # .agent 用のコンテンツ結合
    $AgentContent = $AgentContent + "`n[RULE SOURCE: .clinerules/" + $file.Name + "]`n`n" + $cleanContent + "`n`n============================================================`n"
}

# 5. ファイル書き込み
[System.IO.File]::WriteAllText($AgentsMdFile, $AgentsMdContent, [System.Text.Encoding]::UTF8)
Write-Host "Successfully generated: .AGENTS.md"

[System.IO.File]::WriteAllText($AgentFile, $AgentContent, [System.Text.Encoding]::UTF8)
Write-Host "Successfully generated: .agent"

Write-Host "Synchronization completed successfully!"
