flowchart LR
  subgraph "Original Agent Loop base is cline"
      me[Human]
      DS[DeepSeekV4-pro]
      code[claude code]
      ag[Antigravity]
  end
    

  me -->|全体指示| DS
  
  DS --->|CLI呼び出し| code
  DS --->|CLI呼び出し| ag

  code --->|エージェントループ回答| DS
  ag --->|エージェントループ回答| DS

  ag <-->|相互検証| code